[package]
name = "kdbx"
version = "0.1.0"
authors = ["Sam Wilson <tecywiz121@hotmail.com>"]

[dependencies]
elementtree = "^0.5.0"
openssl = "^0.9.15"
hex = "^0.2.0"
base64 = "^0.6.0"
unicode-normalization = "^0.1.5"
byteorder = "^1.1.0"
flate2 = "^0.2.19"
